# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-16 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.CharField(db_index=True, max_length=255)),
                ('answer', models.CharField(db_index=True, max_length=255)),
                ('number', models.PositiveIntegerField()),
                ('direction', models.CharField(choices=[('A', 'Across'), ('D', 'Down')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Crossword name', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=255)),
                ('editor', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('grid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='crossword',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossword.Publication'),
        ),
        migrations.AddField(
            model_name='clue',
            name='crossword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crossword.Crossword'),
        ),
    ]
